### ISSUE TITLE
Make distinction between default value and implied value if empty in document attributes reference

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoc-docs#1]
There is a difference between a default value (that which the processor assigns if the attribute is not set or unset) and an implied value when the value is empty.

One example of this is the `toc` attribute. The `toc` attribute is not set by default (no default value). If the `toc` attribute is set to an empty string, the processor implies that the value is `auto`. Another example is the `icons` attribute. Again, the attribute is not set by default. But if it is set to an empty value, the processor implies the value is `image`.

(Note however that the processor doesn't actually assign the implied value to the attribute. It just treats the empty value as the same as that value).

In the table, we can continue to use bold to represent the default value. However, for implicit values, they should be listed next to the value of empty. For example:

```
|toc
|_empty_ (auto), auto, left, right, preamble, macro
```

and

```
|icons
|_empty_ (image), image, font
```

I can't think of a case where an attribute has both a default value and an implicit value when blank. Thus far, these have been mutually exclusive (if only by chance).

**Comment by Mogztter** [comment]
I like the suggested notation in the documentation for implied values.

This concept can also be seen as a shortcut/alias but since the processor doesn't actually assign the implied value (i.e. `:toc:` and `:toc: auto` are not strictly equivalents) it's probably better to describe it as implied value.

> I can't think of a case where an attribute has both a default value and an implicit value when blank. 

I can't even think of a case where it would make sense 🤔 
That would probably be confusing to have both.
