### ISSUE TITLE
Missing info about shorthand values for inline pass macro

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoc-docs#37]
Hello!

I can't find the following information in new Asciidoc documentation:

The inline pass macro also accepts shorthand values for specifying substitutions.

* `c` = special characters
* `q` = quotes
* `a` = attributes
* `r` = replacements
* `m` = macros
* `p` = post replacements

https://web.archive.org/web/20201212034130/https://asciidoctor.org/docs/user-manual/#pass-macros

My suggestion is return back old variant of Asciidoc documentation, because new documentation is uncomplete.

**Comment by mojavelinux** [comment]
It appears the paragraph that lists these substitution shorthands on the inline pass macro got inadvertently dropped. I'll see that it's restored.

> My suggestion is return back old variant of Asciidoc documentation, because new documentation is uncomplete.

That's an absurd suggestion. One paragraph is missing and you want to revert the whole 2 year effort? I don't think so. If you want to be part of the solution, you can help improve the documentation where there are errors. Documentation is always imperfect and it requires an ongoing effort to make it as accurate as possible.

**Comment by sindzicat** [comment]
Sorry, my suggestion was unclear. I wanted to suggest not **remove** old version of documentation on site https://asciidoctor.org/docs/user-manual/. Now this page redirects to new version of the documentation.

Anyway, many thanks for the fix!

**Comment by mojavelinux** [comment]
> I wanted to suggest not remove old version of documentation on site asciidoctor.org/docs/user-manual.

That's the suggestion I'm referring to. Absolutely not. That's the documentation that's now out of date and to continue to leave it published would be to share incomplete documentation. It's the documentation at docs.asciidoctor.org that's the most complete and accurate.

We also took tremendous care to redirect section references in the old documentation to the new site so that the transition is seamless and old links continue to work.
