### ISSUE TITLE
Wrongly formatted list continuation examples

### ISSUE THREAD

**Issue by s-leroux** [asciidoctor/asciidoc-docs#49]
In the section ["lists continuation--attaching to an ancestor list"](https://docs.asciidoctor.org/asciidoc/latest/lists/continuation/#attaching-to-an-ancestor-list), the AsciiDoc sources appear on only one line.

In case this is browser-dependant, here is how they are rendered on my screen (Firefox, Linux):

![image](https://user-images.githubusercontent.com/1678974/106316354-deddcd00-626c-11eb-86b5-211561cf53db.png)

**Comment by mojavelinux** [comment]
Thanks for catching this! When I applied the CSS selector for the nowrap role, I inadvertently applied it to pre tags as well. This breaks the formatting of the listing block. I've fixed in the UI and pushed out the change.

Additionally, I'm going to remove the setting on this page to disable wrapping since we don't use that anymore in this site. So we solve it twice.

**Comment by s-leroux** [comment]
Nice. It looks great now!
:+1:
